USE [master]
GO
/****** Object:  Database [BallotDB]    Script Date: 2/4/2019 11:13:46 PM ******/
CREATE DATABASE [BallotDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BallotDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BallotDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BallotDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BallotDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [BallotDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BallotDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BallotDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BallotDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BallotDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BallotDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BallotDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [BallotDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BallotDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BallotDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BallotDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BallotDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BallotDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BallotDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BallotDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BallotDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BallotDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BallotDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BallotDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BallotDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BallotDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BallotDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BallotDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BallotDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BallotDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BallotDB] SET  MULTI_USER 
GO
ALTER DATABASE [BallotDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BallotDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BallotDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BallotDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BallotDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BallotDB] SET QUERY_STORE = OFF
GO
USE [BallotDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [BallotDB]
GO
/****** Object:  Table [dbo].[Autor]    Script Date: 2/4/2019 11:13:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Autor](
	[ID_Autor] [int] NOT NULL,
	[ID_Usuario] [int] NULL,
 CONSTRAINT [PK_Autor] PRIMARY KEY CLUSTERED 
(
	[ID_Autor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categoria]    Script Date: 2/4/2019 11:13:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categoria](
	[ID_Categoria] [int] NOT NULL,
	[Nombre] [nchar](10) NULL,
	[ID_Autor] [int] NULL,
	[Fecha_Creacion] [nchar](10) NULL,
	[ID_Estado] [int] NULL,
 CONSTRAINT [PK_Categoria] PRIMARY KEY CLUSTERED 
(
	[ID_Categoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estado]    Script Date: 2/4/2019 11:13:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estado](
	[ID_Estado] [int] NOT NULL,
	[Titulo] [nchar](10) NULL,
 CONSTRAINT [PK_Estado] PRIMARY KEY CLUSTERED 
(
	[ID_Estado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Nivel]    Script Date: 2/4/2019 11:13:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Nivel](
	[ID_Nivel] [int] NOT NULL,
	[Nombre] [nchar](10) NULL,
 CONSTRAINT [PK_Nivel] PRIMARY KEY CLUSTERED 
(
	[ID_Nivel] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Preguntas]    Script Date: 2/4/2019 11:13:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Preguntas](
	[ID_Pregunta] [int] NOT NULL,
	[Titulo] [nchar](10) NULL,
	[ID_Categoria] [int] NULL,
	[ID_Nivel] [int] NULL,
	[ID_Autor] [int] NULL,
	[ID_Estado] [int] NULL,
	[Fecha_Creacion] [date] NULL,
 CONSTRAINT [PK_Preguntas] PRIMARY KEY CLUSTERED 
(
	[ID_Pregunta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Respuesta_Pregunta]    Script Date: 2/4/2019 11:13:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Respuesta_Pregunta](
	[ID_RespuestaPreg] [int] NOT NULL,
	[ID_Pregunta] [int] NULL,
	[Texto_Respuesta] [nvarchar](50) NULL,
	[RespuestaCorrecta] [nchar](10) NULL,
 CONSTRAINT [PK_Respuesta_Pregunta] PRIMARY KEY CLUSTERED 
(
	[ID_RespuestaPreg] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Respuesta_Pregunta_Usuario]    Script Date: 2/4/2019 11:13:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Respuesta_Pregunta_Usuario](
	[ID_RespuestaUsuario] [int] NOT NULL,
	[ID_RespuestaPreg] [int] NULL,
	[ID_Usuario] [int] NULL,
	[RespuestaSeleccionada] [nchar](10) NULL,
	[Fecha_Respuesta] [date] NULL,
 CONSTRAINT [PK_Respuesta_Pregunta_Usuario] PRIMARY KEY CLUSTERED 
(
	[ID_RespuestaUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 2/4/2019 11:13:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[ID_Usuario] [int] NOT NULL,
	[Nombre] [nvarchar](50) NULL,
	[Email] [nchar](10) NULL,
	[Clave] [nchar](10) NULL,
	[Fecha_Registro] [date] NULL,
	[Usuario_Activo] [nchar](10) NULL,
	[Rol] [nchar](10) NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[ID_Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Autor]  WITH CHECK ADD  CONSTRAINT [FK_Autor_Usuarios] FOREIGN KEY([ID_Usuario])
REFERENCES [dbo].[Usuarios] ([ID_Usuario])
GO
ALTER TABLE [dbo].[Autor] CHECK CONSTRAINT [FK_Autor_Usuarios]
GO
ALTER TABLE [dbo].[Categoria]  WITH CHECK ADD  CONSTRAINT [FK_Categoria_Autor] FOREIGN KEY([ID_Autor])
REFERENCES [dbo].[Autor] ([ID_Autor])
GO
ALTER TABLE [dbo].[Categoria] CHECK CONSTRAINT [FK_Categoria_Autor]
GO
ALTER TABLE [dbo].[Categoria]  WITH CHECK ADD  CONSTRAINT [FK_Categoria_Estado] FOREIGN KEY([ID_Estado])
REFERENCES [dbo].[Estado] ([ID_Estado])
GO
ALTER TABLE [dbo].[Categoria] CHECK CONSTRAINT [FK_Categoria_Estado]
GO
ALTER TABLE [dbo].[Preguntas]  WITH CHECK ADD  CONSTRAINT [FK_Preguntas_Categoria] FOREIGN KEY([ID_Categoria])
REFERENCES [dbo].[Categoria] ([ID_Categoria])
GO
ALTER TABLE [dbo].[Preguntas] CHECK CONSTRAINT [FK_Preguntas_Categoria]
GO
ALTER TABLE [dbo].[Preguntas]  WITH CHECK ADD  CONSTRAINT [FK_Preguntas_Estado] FOREIGN KEY([ID_Estado])
REFERENCES [dbo].[Estado] ([ID_Estado])
GO
ALTER TABLE [dbo].[Preguntas] CHECK CONSTRAINT [FK_Preguntas_Estado]
GO
ALTER TABLE [dbo].[Preguntas]  WITH CHECK ADD  CONSTRAINT [FK_Preguntas_Nivel] FOREIGN KEY([ID_Nivel])
REFERENCES [dbo].[Nivel] ([ID_Nivel])
GO
ALTER TABLE [dbo].[Preguntas] CHECK CONSTRAINT [FK_Preguntas_Nivel]
GO
ALTER TABLE [dbo].[Respuesta_Pregunta]  WITH CHECK ADD  CONSTRAINT [FK_Respuesta_Pregunta_Preguntas] FOREIGN KEY([ID_Pregunta])
REFERENCES [dbo].[Preguntas] ([ID_Pregunta])
GO
ALTER TABLE [dbo].[Respuesta_Pregunta] CHECK CONSTRAINT [FK_Respuesta_Pregunta_Preguntas]
GO
ALTER TABLE [dbo].[Respuesta_Pregunta_Usuario]  WITH CHECK ADD  CONSTRAINT [FK_Respuesta_Pregunta_Usuario_Respuesta_Pregunta] FOREIGN KEY([ID_RespuestaPreg])
REFERENCES [dbo].[Respuesta_Pregunta] ([ID_RespuestaPreg])
GO
ALTER TABLE [dbo].[Respuesta_Pregunta_Usuario] CHECK CONSTRAINT [FK_Respuesta_Pregunta_Usuario_Respuesta_Pregunta]
GO
ALTER TABLE [dbo].[Respuesta_Pregunta_Usuario]  WITH CHECK ADD  CONSTRAINT [FK_Respuesta_Pregunta_Usuario_Usuarios] FOREIGN KEY([ID_Usuario])
REFERENCES [dbo].[Usuarios] ([ID_Usuario])
GO
ALTER TABLE [dbo].[Respuesta_Pregunta_Usuario] CHECK CONSTRAINT [FK_Respuesta_Pregunta_Usuario_Usuarios]
GO
USE [master]
GO
ALTER DATABASE [BallotDB] SET  READ_WRITE 
GO
