USE [master]
GO
/****** Object:  Database [DBBallot]    Script Date: 2/19/2019 7:51:49 PM ******/
CREATE DATABASE [DBBallot]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBBallot', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DBBallot.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBBallot_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DBBallot_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DBBallot] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBBallot].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DBBallot] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBBallot] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBBallot] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBBallot] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBBallot] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBBallot] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DBBallot] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBBallot] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBBallot] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBBallot] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBBallot] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBBallot] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBBallot] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBBallot] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBBallot] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DBBallot] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBBallot] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBBallot] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DBBallot] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DBBallot] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBBallot] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBBallot] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DBBallot] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DBBallot] SET  MULTI_USER 
GO
ALTER DATABASE [DBBallot] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBBallot] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DBBallot] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DBBallot] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DBBallot] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DBBallot] SET QUERY_STORE = OFF
GO
USE [DBBallot]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [DBBallot]
GO
/****** Object:  Table [dbo].[Answers]    Script Date: 2/19/2019 7:51:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Answers](
	[AnswerID] [int] IDENTITY(1,1) NOT NULL,
	[AnswerText] [varchar](max) NULL,
	[QuestionID] [int] NULL,
 CONSTRAINT [PK_Answers] PRIMARY KEY CLUSTERED 
(
	[AnswerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Choices]    Script Date: 2/19/2019 7:51:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Choices](
	[ChoiceID] [int] IDENTITY(1,1) NOT NULL,
	[ChoiceText] [varchar](max) NULL,
	[QuestionID] [int] NULL,
 CONSTRAINT [PK_Choices] PRIMARY KEY CLUSTERED 
(
	[ChoiceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Questions]    Script Date: 2/19/2019 7:51:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Questions](
	[QuestionID] [int] IDENTITY(1,1) NOT NULL,
	[QuestionText] [varchar](max) NULL,
	[QuizID] [int] NULL,
 CONSTRAINT [PK_Questions] PRIMARY KEY CLUSTERED 
(
	[QuestionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Quiz]    Script Date: 2/19/2019 7:51:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Quiz](
	[QuizID] [int] IDENTITY(1,1) NOT NULL,
	[QuizName] [varchar](80) NULL,
	[Category] [varchar](80) NULL,
	[Author] [varchar](80) NULL,
 CONSTRAINT [PK_Quiz] PRIMARY KEY CLUSTERED 
(
	[QuizID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 2/19/2019 7:51:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
	[TypeUser] [varchar](50) NOT NULL,
	[FullName] [varchar](50) NULL,
	[ProfilImage] [varchar](50) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Users]  WITH CHECK ADD CHECK  (([TypeUser]='Admin' OR [TypeUser]='NormalUser'))
GO

CREATE TABLE [dbo].[UserAnswer](
	[UserAnswerID] [int] NOT NULL,
	[UserAnswerText] [varchar](max) NOT NULL,
	[QuestionID] [int] NOT NULL,
 CONSTRAINT [PK_UserAnswer] PRIMARY KEY CLUSTERED 
(
	[UserAnswerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[UserAnswer]  WITH CHECK ADD  CONSTRAINT [FK_UserAnswer_Questions] FOREIGN KEY([QuestionID])
REFERENCES [dbo].[Questions] ([QuestionID])
GO

ALTER TABLE [dbo].[UserAnswer] CHECK CONSTRAINT [FK_UserAnswer_Questions]
GO

ALTER TABLE [dbo].[Answers]  WITH CHECK ADD  CONSTRAINT [FK_Answers_Questions] FOREIGN KEY([QuestionID])
REFERENCES [dbo].[Questions] ([QuestionID])
GO
ALTER TABLE [dbo].[Answers] CHECK CONSTRAINT [FK_Answers_Questions]
GO
ALTER TABLE [dbo].[Choices]  WITH CHECK ADD  CONSTRAINT [FK_Choices_Questions] FOREIGN KEY([QuestionID])
REFERENCES [dbo].[Questions] ([QuestionID])
GO
ALTER TABLE [dbo].[Choices] CHECK CONSTRAINT [FK_Choices_Questions]
GO
ALTER TABLE [dbo].[Questions]  WITH CHECK ADD  CONSTRAINT [FK_Questions_Quiz] FOREIGN KEY([QuizID])
REFERENCES [dbo].[Quiz] ([QuizID])
GO
ALTER TABLE [dbo].[Questions] CHECK CONSTRAINT [FK_Questions_Quiz]
GO
USE [master]
GO
ALTER DATABASE [DBBallot] SET  READ_WRITE 
GO
