//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpBallot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pregunta()
        {
            this.Respuesta_Pregunta = new HashSet<Respuesta_Pregunta>();
        }
    
        public int ID_Pregunta { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> ID_Categoria { get; set; }
        public Nullable<int> ID_Nivel { get; set; }
        public Nullable<int> ID_Autor { get; set; }
        public Nullable<int> ID_Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Nivel Nivel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta_Pregunta> Respuesta_Pregunta { get; set; }
    }
}
