//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpBallot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta_Pregunta_Usuario
    {
        public int ID_RespuestaUsuario { get; set; }
        public Nullable<int> ID_RespuestaPreg { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public string RespuestaSeleccionada { get; set; }
        public Nullable<System.DateTime> Fecha_Respuesta { get; set; }
    
        public virtual Respuesta_Pregunta Respuesta_Pregunta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
