//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpBallot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta_Pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respuesta_Pregunta()
        {
            this.Respuesta_Pregunta_Usuario = new HashSet<Respuesta_Pregunta_Usuario>();
        }
    
        public int ID_RespuestaPreg { get; set; }
        public Nullable<int> ID_Pregunta { get; set; }
        public string Texto_Respuesta { get; set; }
        public string RespuestaCorrecta { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta_Pregunta_Usuario> Respuesta_Pregunta_Usuario { get; set; }
    }
}
